name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: linux deps
      run: |
        sudo apt-get install \
          g++-11 \
          clang-12 \
          autoconf \
          automake \
          autotools-dev \
          autopoint \
          libtool \
          pkg-config \
          libssl-dev \
          libc-ares-dev \
          zlib1g-dev \
          libsqlite3-dev \
          libssh2-1-dev \
          libcppunit-dev

    - name: autoreconf
      run: autoreconf -i
      
    - name: configure with binary
      run: ./configure ARIA2_STATIC=yes

    - name: Install dependencies
      run: make
    
    - name: aria2 binary upload
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        #name: # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: ./src/aria2c
        # The desired behavior if no files are found using the provided path.
